export const ROUTE = 'route'
export const USERINFO = 'user_info'
export const PROCESSSTATUS = 'process_status'
export const PROCESSCREATORID = 'process_creatorId'
export const PROCESSROLE = 'process_role'
export const PAGESTATUS = 'page_status'
