export const ROUTE = 'route'
export const USERINFO = 'user_info'
export const PROCESSSTATUS = 'process_status'
export const PROCESSCREATORID = 'process_creatorId'
export const PROCESSROLE = 'process_role'
export const CURRENTSTATUS = 'current_status'

export const SET_INFO = 'set_info'
export const SET_BUSITYPE = 'set_busiType'
export const SET_MODULES = 'set_modules'
