export const PRFLAG = 'pr_flag'
export const CONTRACTTYPE = 'contract_type'
export const CONTRACTBUSINESSTYPE = 'contract_business_type'
export const SERVICEFLAG = 'service_flag'
export const TEXTTYPE = 'text_type'
